---
- name: install docker and also softwares
  hosts: all
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: download docker
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: install docker
      shell: sh get-docker.sh
    - name: install docker-py
      shell: pip3 install docker-py