---
- name: install s/w applications
  hosts: all
  tasks:
    - name: install s/w's
      apt:
        name: "{{item}}"
        state: absent
        update_cache: yes
      with_items:
        - tree
        - git
        - maven
...