---
- name: install sw apps
  hosts: all
  tasks:
    - name: install sws
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree ,b:present, c:yes}
        - {a: git ,b:present, c:yes}
        - {a: maven ,b:present, c:yes}

...
