---
- name: install jenkins
  hosts: jenkins
  gather_facts: yes
  become: yes
  tasks:
    - name: install required sws
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: openjdk-11-jdk, b: yes}
        - {a: git, b: no}
        - {a: maven, b: no}
    - name: download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.361.2/jenkins.war
        dest: /home/ubuntu
- name: install tomcat and requird sws
  hosts: servers
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: tomcat9 , b: yes}
        - {a: tomcat9-admin, b: no}
    - name: copy the tomcat-users.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9
      notify: restart tomcat
  handlers:
    - name: restart tomcat
      service:
        name: tomcat9
        state: restarted
...