---
- name: install docker and also softwares
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    - name: download docker and install docker and install pip3
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - pip3 install docker-py

...