---
- name: install jenkins
  hosts: jenkins
  tasks:
    - name: install required sws
      apt:
        name: "{{item.a}}"
        state: present
        update_cache: "{{item.b}}"
      with_items:
        - {a: openjdk-11-jdk, b: yes}
        - {a: git, b: no}
        - {a: maven, b: no}
    - name: download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.361.2/jenkins.war
        dest: /home/ubuntu
...