---
- name: working on containers
  hosts: all
  tasks:
    - name: create a container tomcat
      docker_container:
        name: appserver
        image: tomee
    - name: stop container
      docker_container:
        name: appserver
        state: stopped
    - name: delete the container
      docker_container:
        name: appserver
        state: absent
...