---
- name: capture os info
  hosts: all
  tasks:
    - name: display os name
      debug: msg = "{{ansible_distribution}}"
    - name: display version
      debug: msg= "{{ansible_distribution_version}}"
...