---
- name: create 3 nginx containers
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: create 3 nginx containers
      docker_container:
        name: "container{{item}}"
        image: nginx
      with_sequence: count=3
...