---
- name: error handling
  hosts: all
  tasks:
    - block:
        - name: install tree using apt
          apt:
            name: tree
            state: present
            update_cache: yes
      rescue:
        - name: install using yum
          yum:
            name: tree
            state: present
            update_cache: yes
      always:
        - name: print success message
          debug:
            msg: "Installation Successful"

...