---
- name: install jenkins
  hosts: all
  tasks:
    - name: install required sws
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-11-jdk, b: present,c: yes}
        - {a: git, b: present,c: no}
        - {a: maven, b: present,c: no}
    - name: download jenkins
      get_url:
        url: https://get.jenkins.io/war-stable/2.361.2/jenkins.war
        dest: /home/ubuntu

...
